image: ruby:2.4.2 

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install 


build_job:
  image: docker:19.03
  stage: build
  before_script:
    - docker info
    - echo 'CI_SERVER_HOST- '$CI_SERVER_HOST
    - echo 'CI_COMMIT_REF_NAME- '$CI_COMMIT_REF_NAME
    - echo 'CI_PIPELINE_IID - '$CI_PIPELINE_IID
  script:
    - docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID ./reddit
    - docker tag reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID ivansscrobot/gitlab-reddit:$CI_PIPELINE_IID
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - docker push ivansscrobot/gitlab-reddit:$CI_PIPELINE_IID
  artifacts:
    paths:
      - reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb 
    - hostname

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'
    - hostname

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
    - hostname
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - hostname
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master 

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
    - hostname
  environment:
    name: stage
    url: https://beta.example.com 

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
   - echo 'Deploy'
   - hostname
  environment:
    name: production
    url: https://example.com
