global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ivan_scrobot'
  - send_resolved: true