version: "3"

services:
  post_db:
    image: mongo:3.2
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net: 
        aliases:
          - post_db
          - comment_db 
  ui:
    image: ${USERNAME}/ui:${UI_TAG}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${APP_PORT}:9292/tcp
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${UI_TAG}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"  
    networks:
      - front_net
      - back_net 
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post     
  comment:
    image: ${USERNAME}/comment:${UI_TAG}  
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
    networks:
      - front_net
      - back_net
  
volumes:
  post_db:

networks:
  front_net:
  back_net:
