version: "3"

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net: 
        aliases:
          - post_db
          - comment_db 
  ui:
    image: ${USERNAME}/ui
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post
    networks:
      - front_net
      - back_net    
  comment:
    image: ${USERNAME}/comment
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
      #- /home/ivan/git/IvanSScrobot_microservices/monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
  mongo-exporter:
    image: ${USERNAME}/mongoexporter
    ports:
      - '9216:9216'
    networks:
      - back_net  

volumes:
  prometheus_data:
  post_db:

networks:
  front_net:
  back_net:
