plugin: gcp_compute             # name the plugin you want to use (use `ansible-doc -t inventory -l` to list available plugins)
projects:
  - docker-is           # Id of your gcp project

groups:
  gitlab-runner: "'gitlab-runner' in name"
  gitlab-ci: "'gitlab-ci' in name"

#hostnames:                # A list of options that describe the ordering for which hostnames should be assigned. Currently supported hostnames are 'public_ip', 'private_ip', or 'name'.
#  - name
filters: []
auth_kind: serviceaccount       # gcp authentication kind. with service account you should provide the service account json key file to authenticate
service_account_file: service_account_file.json   # Service account json keyfile
