# vars for gitlab-runners
gitlab_runner_registration_token: 'Js-XFh_VyzvrJTPx9Gi9'
gitlab_runner_coordinator_url: "http://104.198.248.218/"
gitlab_runner_package_name: gitlab-runner
gitlab_runner_runners:
  - name: "Privileged docker runner"
    executor: docker
    docker_image: "docker:19.03"
    tags:
      - docker
      - linux
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    docker_privileged: false