---
- hosts: gitlab 
  become: true
  vars:
    default_container_name: gitlab.example.com
    default_container_image: gitlab/gitlab-ce:latest 


  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-pip', 'python-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs  
    
    - name: Touch docker-compose.yml
      file:
        path: /srv/gitlab/docker-compose.yml
        state: touch
        mode: u=rw,g=r,o=r

    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates container, using default values
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        restart: yes
        tty: yes
        ports:
          - "80:80"
          - "443:443"
          - "2222:22"
        volumes:
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab
        env:
          GITLAB_OMNIBUS_CONFIG: external_url 'http://35.239.202.107'
        
